version: '3.8'

services:
  prompt-optimizer:
    build: .
    ports:
      - "9090:9090"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s