export const useCases = [
    { id: 'complex-qa', name: 'Complex Question Answering', icon: '❓', description: 'Multi-hop queries requiring information synthesis' },
    { id: 'math', name: 'Mathematical Problem Solving', icon: '🔢', description: 'Calculations and mathematical reasoning' },
    { id: 'code', name: 'Code Generation & Debugging', icon: '🐛', description: 'Writing and fixing code' },
    { id: 'planning', name: 'Strategic Planning', icon: '📋', description: 'Developing comprehensive plans and strategies' },
    { id: 'analysis', name: 'Analysis & Evaluation', icon: '📊', description: 'Deep analysis of data or situations' },
    { id: 'content', name: 'Content Creation', icon: '✍️', description: 'Writing and creative content generation' },
    { id: 'research', name: 'Research & Investigation', icon: '🔬', description: 'In-depth research on topics' },
    { id: 'creative', name: 'Creative Problem Solving', icon: '🎨', description: 'Innovative and creative solutions' },
    { id: 'data-analysis', name: 'Data Analysis', icon: '📈', description: 'Processing and analyzing data' },
    { id: 'scientific', name: 'Scientific Computing', icon: '🧪', description: 'Scientific calculations and modeling' },
    { id: 'financial', name: 'Financial Analysis', icon: '💰', description: 'Financial calculations and planning' },
    { id: 'decision-making', name: 'Decision Making', icon: '🤔', description: 'Complex decision analysis' },
    { id: 'automation', name: 'Task Automation', icon: '🤖', description: 'Automating complex workflows' },
    { id: 'optimization', name: 'Optimization Problems', icon: '⚡', description: 'Finding optimal solutions' },
    { id: 'validation', name: 'Validation & Review', icon: '✅', description: 'Checking and validating work' },
    { id: 'policy', name: 'Policy Analysis', icon: '📜', description: 'Analyzing policies and regulations' },
    { id: 'innovation', name: 'Innovation Strategy', icon: '💡', description: 'Developing innovative approaches' },
    { id: 'investigation', name: 'Investigation', icon: '🔍', description: 'Investigating complex topics' },
    { id: 'review', name: 'Peer Review', icon: '👥', description: 'Reviewing and improving work' },
    { id: 'complex-analysis', name: 'Complex Systems Analysis', icon: '🌐', description: 'Analyzing complex interconnected systems' },
    // Safety & Guardrails use cases
    { id: 'content-moderation', name: 'Content Moderation', icon: '🛡️', description: 'Filtering and moderating user-generated content' },
    { id: 'ethical-ai', name: 'Ethical AI', icon: '⚖️', description: 'Ensuring AI systems behave ethically' },
    { id: 'safety-critical', name: 'Safety-Critical Systems', icon: '🚨', description: 'High-stakes applications requiring safety' },
    { id: 'compliance', name: 'Regulatory Compliance', icon: '📋', description: 'Meeting legal and regulatory requirements' },
    { id: 'brand-safety', name: 'Brand Safety', icon: '🛡️', description: 'Protecting brand reputation and values' },
    { id: 'platform-safety', name: 'Platform Safety', icon: '🔒', description: 'Ensuring platform security and safety' },
    { id: 'security', name: 'Security', icon: '🔐', description: 'Cybersecurity and system protection' },
    { id: 'prompt-injection-defense', name: 'Prompt Injection Defense', icon: '🛡️', description: 'Defending against prompt injection attacks' },
    { id: 'data-validation', name: 'Data Validation', icon: '✔️', description: 'Validating and verifying data integrity' },
    { id: 'system-protection', name: 'System Protection', icon: '🔒', description: 'Protecting system resources and integrity' },
    { id: 'high-stakes-decisions', name: 'High-Stakes Decisions', icon: '⚠️', description: 'Critical decisions with significant impact' },
    { id: 'medical-advice', name: 'Medical Guidance', icon: '🏥', description: 'Health and medical information systems' },
    { id: 'quality-assurance', name: 'Quality Assurance', icon: '✅', description: 'Ensuring output quality and reliability' },
    // Chaining use cases
    { id: 'content-creation', name: 'Content Creation', icon: '📝', description: 'Multi-step content generation workflows' },
    { id: 'data-processing', name: 'Data Processing', icon: '⚙️', description: 'Complex data transformation pipelines' },
    { id: 'workflow-automation', name: 'Workflow Automation', icon: '🔄', description: 'Automated business process workflows' },
    { id: 'multi-step-analysis', name: 'Multi-Step Analysis', icon: '📊', description: 'Complex analytical workflows' },
    { id: 'consensus-building', name: 'Consensus Building', icon: '🤝', description: 'Building agreement through multiple perspectives' },
    { id: 'rapid-ideation', name: 'Rapid Ideation', icon: '💡', description: 'Fast generation of multiple ideas' },
    { id: 'personalization', name: 'Personalization', icon: '👤', description: 'Customized user experiences' },
    { id: 'adaptive-workflows', name: 'Adaptive Workflows', icon: '🔀', description: 'Dynamic, context-sensitive processes' },
    { id: 'decision-trees', name: 'Decision Trees', icon: '🌳', description: 'Complex decision-making flows' },
    { id: 'user-interfaces', name: 'User Interfaces', icon: '🖥️', description: 'Interactive user experience flows' },
    { id: 'content-refinement', name: 'Content Refinement', icon: '✨', description: 'Iterative content improvement' },
    { id: 'creative-iteration', name: 'Creative Iteration', icon: '🎨', description: 'Iterative creative development' },
    { id: 'quality-improvement', name: 'Quality Improvement', icon: '📈', description: 'Continuous quality enhancement' },
    { id: 'project-planning', name: 'Project Planning', icon: '📅', description: 'Complex project organization' },
    { id: 'research-synthesis', name: 'Research Synthesis', icon: '📚', description: 'Combining multiple research sources' },
    { id: 'system-design', name: 'System Design', icon: '🏗️', description: 'Complex system architecture planning' }
  ];