version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  # Optional: Redis for caching execution results
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped